image: maven:3.3.9

pipelines:
  branches:
    master:
      - step:
          name: Run Tests
          caches:
            - maven
          script:
            - mvn test
      - step:
          name: Push Docker Image to Registry
          caches:
            - maven
          services:
            - docker
          script:
            - mvn package -Dmaven.test.skip=true
            - docker build -t milchkarton/movie:movie-backend-v$BITBUCKET_BUILD_NUMBER .
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker push $DOCKER_USER/movie:movie-backend-v$BITBUCKET_BUILD_NUMBER

  default:
    - step:
        name: Verify that branch build is success
        caches:
          - maven
        script:
          - mvn clean install
